# Customer Churn Analytics, Revenue Risk & Retention Optimization
## Project Goal

This project analyzes customer churn for a telecom company.

The goal is to understand:
- Which customers are leaving
- Why customers are leaving
- How much revenue is at risk
- Which customers are likely to churn
- What business actions can reduce churn

This project uses Python, SQL, Tableau, and Machine Learning to create business insights and retention recommendations.

### 1. Import Librarie

In [139]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [140]:
df = pd.read_csv(r"E:\data Analystic\customer-churn-prediction-retention-analysis\data\raw\Telco-Customer-Churn.csv")

In [141]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [142]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

### 2. Initial Data Understanding

We will check:
- How many rows and columns are in the dataset
- What column names are available
- Basic information about each column

In [143]:
df.shape

(7043, 21)

In [144]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

### 3. Data Quality Checks

We will check:
- Missing values
- Duplicate rows
- Wrong data types

In [146]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [147]:
df.duplicated().sum()

np.int64(0)

In [148]:
df["TotalCharges"].dtype

dtype('O')

### 4. Data Cleaning

In [149]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [150]:
df["TotalCharges"].dtype

dtype('float64')

In [151]:
df["TotalCharges"].isnull().sum()

np.int64(11)

In [152]:
df[df["TotalCharges"].isnull()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [153]:
df = df.dropna(subset=["TotalCharges"])

In [154]:
df["TotalCharges"].isnull().sum()

np.int64(0)

In [155]:
df[df["TotalCharges"].isnull()]

Empty DataFrame
Columns: [customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

[0 rows x 21 columns]

In [156]:
df = df.dropna(subset=["TotalCharges"])

In [157]:
df["TotalCharges"].isnull().sum()

np.int64(0)

In [158]:
df.shape

(7032, 21)

In [159]:
df = df.reset_index(drop=True)

### 5. Feature Engineering

These columns will help us analyze customer churn, revenue risk, and customer segments.
New columns we will create:
- ChurnFlag
- EstimatedAnnualRevenue
- TenureGroup

In [160]:
df["ChurnFlag"] = df["Churn"].map({"Yes": 1, "No": 0})

In [161]:
df["EstimatedAnnualRevenue"] = df["MonthlyCharges"] * 12

In [162]:
def tenure_group(tenure):
    if tenure <= 12:
        return "0-12 Months"
    elif tenure <= 24:
        return "13-24 Months"
    elif tenure <= 48:
        return "25-48 Months"
    else:
        return "49+ Months"

df["TenureGroup"] = df["tenure"].apply(tenure_group)

In [163]:
df[["Churn", "ChurnFlag", "MonthlyCharges", "EstimatedAnnualRevenue", "tenure", "TenureGroup"]].head()

,Churn,ChurnFlag,MonthlyCharges,EstimatedAnnualRevenue,tenure,TenureGroup
0,No,0,29.85,358.2,1,0-12 Months
1,No,0,56.95,683.4,34,25-48 Months
2,Yes,1,53.85,646.2,2,0-12 Months
3,No,0,42.30,507.6,45,25-48 Months
4,Yes,1,70.70,848.4,2,0-12 Months

In [164]:
df["RevenueAtRisk"] = df["EstimatedAnnualRevenue"] * df["ChurnFlag"]

In [165]:
def risk_segment(row):
    if row["Contract"] == "Month-to-month" and row["MonthlyCharges"] >= 70 and row["tenure"] <= 12:
        return "High Risk"
    elif row["Contract"] == "Month-to-month":
        return "Medium Risk"
    else:
        return "Low Risk"

df["CustomerRiskSegment"] = df.apply(risk_segment, axis=1)

In [166]:
df[["Contract", "MonthlyCharges", "tenure", "EstimatedAnnualRevenue", "RevenueAtRisk", "CustomerRiskSegment", "Churn"]].head()

,Contract,MonthlyCharges,tenure,EstimatedAnnualRevenue,RevenueAtRisk,CustomerRiskSegment,Churn
0,Month-to-month,29.85,1,358.2,0.0,Medium Risk,No
1,One year,56.95,34,683.4,0.0,Low Risk,No
2,Month-to-month,53.85,2,646.2,646.2,Medium Risk,Yes
3,One year,42.30,45,507.6,0.0,Low Risk,No
4,Month-to-month,70.70,2,848.4,848.4,High Risk,Yes

### 6. Exploratory Data Analysis

In [167]:
df["Churn"].value_counts()

Churn
No     5163
Yes    1869
Name: count, dtype: int64

In [168]:
churn_rate = df["ChurnFlag"].mean() * 100
churn_rate

np.float64(26.578498293515356)

## Business Insight: Overall Churn Rate

The overall churn rate is approximately 26.58%.
This means about 27 out of every 100 customers left the company.
From a business point of view, this is important because customer churn directly affects recurring revenue. Reducing churn can help the company protect customer value and improve long-term revenue.

In [169]:
df.groupby("Contract")["ChurnFlag"].mean() * 100

Contract
Month-to-month    42.709677
One year          11.277174
Two year           2.848665
Name: ChurnFlag, dtype: float64

In [170]:
contract_churn = df.groupby("Contract")["ChurnFlag"].mean().sort_values(ascending=False) * 100

contract_churn

Contract
Month-to-month    42.709677
One year          11.277174
Two year           2.848665
Name: ChurnFlag, dtype: float64

### Business Insight: Churn by Contract Type

Customers with month-to-month contracts have the highest churn rate.
This means customers without a long-term contract are more likely to leave.
From a business point of view, the company should focus on moving month-to-month customers into one-year or two-year contracts by offering discounts, loyalty benefits, or better service packages.

In [171]:
payment_churn = df.groupby("PaymentMethod")["ChurnFlag"].mean().sort_values(ascending=False) * 100

payment_churn

PaymentMethod
Electronic check             45.285412
Mailed check                 19.201995
Bank transfer (automatic)    16.731518
Credit card (automatic)      15.253123
Name: ChurnFlag, dtype: float64

### Business Insight: Churn by Payment Method

Customers using electronic check have a higher churn rate compared to other payment methods.
This may mean that customers using electronic check are less committed or may experience more payment friction.
From a business point of view, the company could encourage customers to use automatic payment methods such as credit card or bank transfer. This may help improve customer retention.

In [172]:
tenure_churn = df.groupby("TenureGroup")["ChurnFlag"].mean().sort_values(ascending=False) * 100

tenure_churn

TenureGroup
0-12 Months     47.678161
13-24 Months    28.710938
25-48 Months    20.388959
49+ Months       9.513176
Name: ChurnFlag, dtype: float64

### Business Insight: Churn by Tenure Group

Customers with lower tenure have a higher churn rate.
This means newer customers are more likely to leave compared to long-term customers.
From a business point of view, the company should focus on the first 12 months of the customer journey. Better onboarding, early support, welcome offers, and loyalty programs can help reduce early customer churn.

In [173]:
total_annual_revenue = df["EstimatedAnnualRevenue"].sum()

print(f"Total Estimated Annual Revenue: ${total_annual_revenue:,.2f}")

Total Estimated Annual Revenue: $5,467,932.00

In [174]:
total_revenue_at_risk = df["RevenueAtRisk"].sum()

print(f"Total Estimated Annual Revenue at Risk: ${total_revenue_at_risk:,.2f}")

Total Estimated Annual Revenue at Risk: $1,669,570.20

### Business Insight: Revenue at Risk

The revenue-at-risk metric estimates how much annual revenue is connected to customers who churned.
This helps business leaders understand churn not only as a customer problem, but also as a revenue problem.
From a business point of view, reducing churn among high-value customers can help protect annual revenue and improve long-term customer value.

In [175]:
df["CustomerRiskSegment"].value_counts()

CustomerRiskSegment
Low Risk       3157
Medium Risk    3015
High Risk       860
Name: count, dtype: int64

In [176]:
risk_churn = df.groupby("CustomerRiskSegment")["ChurnFlag"].mean().sort_values(ascending=False) * 100

risk_churn

CustomerRiskSegment
High Risk      69.186047
Medium Risk    35.157546
Low Risk        6.778587
Name: ChurnFlag, dtype: float64

In [177]:
risk_revenue = df.groupby("CustomerRiskSegment")["RevenueAtRisk"].sum().sort_values(ascending=False)

risk_revenue

CustomerRiskSegment
Medium Risk    851652.0
High Risk      598513.2
Low Risk       219405.0
Name: RevenueAtRisk, dtype: float64

### Business Insight: Customer Risk Segment

The customer risk segment analysis helps identify which customer groups need attention first.
High-risk customers are usually customers with:
- Month-to-month contracts
- Higher monthly charges
- Lower tenure
These customers are more likely to churn and may create higher revenue risk.
From a business point of view, the company should prioritize high-risk and medium-risk customers for retention campaigns, special offers, and proactive customer support.

In [178]:
df[[
    "customerID",
    "Contract",
    "PaymentMethod",
    "tenure",
    "TenureGroup",
    "MonthlyCharges",
    "EstimatedAnnualRevenue",
    "RevenueAtRisk",
    "CustomerRiskSegment",
    "Churn"
]].head()

,customerID,Contract,PaymentMethod,tenure,TenureGroup,MonthlyCharges,EstimatedAnnualRevenue,RevenueAtRisk,CustomerRiskSegment,Churn
0,7590-VHVEG,Month-to-month,Electronic check,1,0-12 Months,29.85,358.2,0.0,Medium Risk,No
1,5575-GNVDE,One year,Mailed check,34,25-48 Months,56.95,683.4,0.0,Low Risk,No
2,3668-QPYBK,Month-to-month,Mailed check,2,0-12 Months,53.85,646.2,646.2,Medium Risk,Yes
3,7795-CFOCW,One year,Bank transfer (automatic),45,25-48 Months,42.30,507.6,0.0,Low Risk,No
4,9237-HQITU,Month-to-month,Electronic check,2,0-12 Months,70.70,848.4,848.4,High Risk,Yes

In [179]:
df.to_csv(r"E:\data Analystic\customer-churn-prediction-retention-analysis\data\cleaned\cleaned_customer_churn.csv", index=False)

### 7. Machine Learning Model

In [180]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [181]:
ml_df = df.copy()

In [182]:
ml_df = ml_df.drop("customerID", axis=1)

In [183]:
X = ml_df.drop(["Churn", "ChurnFlag", "RevenueAtRisk"], axis=1)
y = ml_df["ChurnFlag"]

In [184]:
X = pd.get_dummies(X, drop_first=True)

In [185]:
X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y, 
    test_size=0.2, 
    random_state=42
)

In [186]:
rf_model = RandomForestClassifier(random_state=42)

In [187]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [188]:
y_pred = rf_model.predict(X_test)

In [189]:
accuracy = accuracy_score(y_test, y_pred)

print(f"Model Accuracy: {accuracy:.2%}")

Model Accuracy: 78.54%

In [190]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.90      0.86      1033
           1       0.63      0.48      0.54       374

    accuracy                           0.79      1407
   macro avg       0.73      0.69      0.70      1407
weighted avg       0.77      0.79      0.78      1407

In [191]:
confusion_matrix(y_test, y_pred)

array([[927, 106],
       [196, 178]])

In [192]:
feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf_model.feature_importances_
}).sort_values(by="Importance", ascending=False)

feature_importance.head(10)

                           Feature  Importance
3                     TotalCharges    0.148229
1                           tenure    0.132218
2                   MonthlyCharges    0.126482
4           EstimatedAnnualRevenue    0.123487
34    CustomerRiskSegment_Low Risk    0.052452
11     InternetService_Fiber optic    0.035014
29  PaymentMethod_Electronic check    0.030599
5                      gender_Male    0.024414
27            PaperlessBilling_Yes    0.022296
6                      Partner_Yes    0.020734

### Business Insight: Machine Learning Model

The machine learning model helps identify customers who are likely to churn.
The feature importance results show which customer attributes are most useful for predicting churn.
From a business point of view, these insights can help the company prioritize retention actions for customers with higher churn risk, such as customers with month-to-month contracts, lower tenure, or higher monthly charges.

In [193]:
churn_probability = rf_model.predict_proba(X)[:, 1]

In [194]:
df["ChurnProbability"] = churn_probability

In [195]:
def predicted_risk(probability):
    if probability >= 0.70:
        return "High Predicted Risk"
    elif probability >= 0.40:
        return "Medium Predicted Risk"
    else:
        return "Low Predicted Risk"

df["PredictedRiskLevel"] = df["ChurnProbability"].apply(predicted_risk)

In [196]:
df[[
    "customerID",
    "Contract",
    "tenure",
    "MonthlyCharges",
    "Churn",
    "ChurnProbability",
    "PredictedRiskLevel"
]].head(10)

,customerID,Contract,tenure,MonthlyCharges,Churn,ChurnProbability,PredictedRiskLevel
0,7590-VHVEG,Month-to-month,1,29.85,No,0.25,Low Predicted Risk
1,5575-GNVDE,One year,34,56.95,No,0.01,Low Predicted Risk
2,3668-QPYBK,Month-to-month,2,53.85,Yes,0.79,High Predicted Risk
3,7795-CFOCW,One year,45,42.30,No,0.00,Low Predicted Risk
4,9237-HQITU,Month-to-month,2,70.70,Yes,0.92,High Predicted Risk
5,9305-CDSKC,Month-to-month,8,99.65,Yes,0.98,High Predicted Risk
6,1452-KIOVK,Month-to-month,22,89.10,No,0.14,Low Predicted Risk
7,6713-OKOMC,Month-to-month,10,29.75,No,0.08,Low Predicted Risk
8,7892-POOKP,Month-to-month,28,104.80,Yes,0.71,High Predicted Risk
9,6388-TABGU,One year,62,56.15,No,0.01,Low Predicted Risk

In [197]:
df.to_csv(
    r"E:\data Analystic\customer-churn-prediction-retention-analysis\data\cleaned\customer_churn_with_predictions.csv",
    index=False
)

### Business Insight: Churn Probability

The model-generated churn probability gives each customer a risk score.
This helps the business move from basic reporting to proactive decision-making.
Instead of only seeing which customers already churned, the company can identify active customers who may churn in the future and prioritize them for retention actions.

### 8. Business Recommendations

### Key Findings

1. The overall churn rate is approximately 26.58%.

2. Month-to-month customers have the highest churn rate.

3. Customers using electronic check show higher churn compared to other payment methods.

4. Newer customers with lower tenure are more likely to churn.

5. High-risk customers are often linked to month-to-month contracts, higher monthly charges, and lower tenure.

6. Revenue-at-risk analysis shows that churn is not only a customer problem, but also a revenue problem.

7. The machine learning model provides churn probability scores that can help identify customers who may leave in the future.

### Recommendations

1. Target month-to-month customers with contract upgrade offers.
The company should encourage month-to-month customers to move into one-year or two-year contracts by offering discounts, loyalty rewards, or bundled service packages.

2. Focus on new customers during the first 12 months.
New customers have a higher churn risk. The company should improve onboarding, provide early support, and send welcome offers during the first year.

3. Reduce payment friction.
Customers using electronic check have higher churn. The company should encourage automatic payment methods such as credit card or bank transfer.

4. Prioritize high-value customers at risk.
The business should focus retention efforts on customers with high monthly charges and high predicted churn probability because they represent higher revenue risk.

5. Use churn probability for proactive retention.
The company can use model-generated churn probability to identify customers before they leave and target them with personalized retention campaigns.

6. Monitor churn and revenue risk through Tableau.
A Tableau dashboard should be used to track churn rate, revenue at risk, customer segments, and predicted risk levels for business decision-making.

### 9. Export Final Files

In [198]:
print("Files saved successfully:")
print("1. cleaned_customer_churn.csv")
print("2. customer_churn_with_predictions.csv")

Files saved successfully:
1. cleaned_customer_churn.csv
2. customer_churn_with_predictions.csv